codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  range: 80..100
  round: down
  precision: 2
  status:
    changes: false
    project:
      default:
        target: 94.0
        threshold: 0.1
      fully_covered:
        target: 99.95
        paths:
          - OpenQA/
          - backend/
          - consoles/console.pm
          - consoles/VMWare.pm
          - consoles/VNC.pm
          - consoles/localXvnc.pm
          - consoles/network_console.pm
          - consoles/serial_screen.pm
          - consoles/sshSerial.pm
          - consoles/sshIucvconn.pm
          - consoles/virtio_terminal.pm
          - bmwqemu.pm
          - log.pm
          - mmapi.pm
          - osutils.pm
          - signalblocker.pm
          - testapi.pm
          - t/
          - xt/
    patch:
      default:
        branches: null
fixes:
  - "/opt/::"
